[phases.setup]
nixPkgs = ["...", "cairo", "pango", "gdk-pixbuf", "libffi", "shared-mime-info", "postgresql"]

[phases.install]
cmds = ["pip install --no-cache-dir -r requirements.txt"]

[start]
cmd = "gunicorn run:app --bind 0.0.0.0:$PORT --workers 2 --timeout 120 --preload"
